import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chubGothic = localFont({
  src: "../fonts/ChubGothic-Regular.ttf",
  variable: "--font-chub",
  display: "swap",
});

const coolvetica = localFont({
  src: "../fonts/CoolveticaRg-Regular.ttf",
  variable: "--font-coolvetica",
  display: "swap",
});

const sebino = localFont({
  src: "../fonts/Sebino-Regular.ttf",
  variable: "--font-sebino",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${chubGothic.variable} ${coolvetica.variable} ${sebino.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
